### ISSUE TITLE
Problems with compiling under VS 2022

### ISSUE THREAD

**Issue by ViperAcidZX** [MainMemory/SA2NoBattle#1]
I wanted to try and compile this on Visual Studio Community 2022 and I want to build a version that restores the alternate backgrounds from the GameCube version and/or SA2B intro but I keep running into problems with the solution complaining about not having the required tools and registry nonsense that won't let me just compile the mod. I wasted 7.4 GB of disk space for the 2017 build tools for nothing while trying to bust my head to get this solution to cooperate but nothing works. At this point I'm begging pre-compiled versions that retains the GameCube menu character backgrounds and/or the SA2B intro since this solution will not work for me.

**Comment by MainMemory** [comment]
You need to install `Windows XP support for Visual Studio 2017` to build the project; or you can open the project's properties and change the `Platform Toolset` option to one of the options you have installed.

**Comment by ViperAcidZX** [comment]
This worked, thank you MainMemory!
